// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjiX7YVzkscr8Dl5kJ8qVsvnMpy7sos8s',
    appId: '1:530558936648:web:5e4a13af996ab770369a7d',
    messagingSenderId: '530558936648',
    projectId: 'fir-e88fa',
    authDomain: 'fir-e88fa.firebaseapp.com',
    storageBucket: 'fir-e88fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4I7020SA_dqAcdxYkWTQFueLP5uJPiaw',
    appId: '1:530558936648:android:580c7dbb1a831d57369a7d',
    messagingSenderId: '530558936648',
    projectId: 'fir-e88fa',
    storageBucket: 'fir-e88fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBogjHTXOsFzuYWqjMKHu4UdY2q6DmPFYA',
    appId: '1:530558936648:ios:d846267816f81226369a7d',
    messagingSenderId: '530558936648',
    projectId: 'fir-e88fa',
    storageBucket: 'fir-e88fa.firebasestorage.app',
    iosBundleId: 'com.example.feedbackSystemFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBogjHTXOsFzuYWqjMKHu4UdY2q6DmPFYA',
    appId: '1:530558936648:ios:d846267816f81226369a7d',
    messagingSenderId: '530558936648',
    projectId: 'fir-e88fa',
    storageBucket: 'fir-e88fa.firebasestorage.app',
    iosBundleId: 'com.example.feedbackSystemFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjiX7YVzkscr8Dl5kJ8qVsvnMpy7sos8s',
    appId: '1:530558936648:web:d5c569eb1b12f31b369a7d',
    messagingSenderId: '530558936648',
    projectId: 'fir-e88fa',
    authDomain: 'fir-e88fa.firebaseapp.com',
    storageBucket: 'fir-e88fa.firebasestorage.app',
  );
}
